name: NotTowerDefense
version: '${project.version}'
main: fr.not_here.not_tower_defense.NotTowerDefense


commands:
  td:
    description: Main command used to run the game, using /td only will open the ui
    aliases: [towerdefense, nottowerdefense, not_tower_defense]
    permission: not_tower_defense.td
    permission-message: You don't have the permission to run the game